"""Architecture boundary tests generated by spaghetti-guard."""

import os
import sys

from pytestarch import Rule, get_evaluable_architecture

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
src_dir = os.path.join(project_root, "src")
if not os.path.exists(src_dir):
    src_dir = project_root

if src_dir not in sys.path:
    sys.path.insert(0, src_dir)

evaluable = get_evaluable_architecture(project_root, src_dir)


def test_models_do_not_import_service() -> None:
    rule = (
        Rule()
        .modules_that()
        .have_name_matching(".*models")
        .should_not()
        .import_modules_that()
        .have_name_matching(".*service")
    )
    rule.assert_applies(evaluable)
